### ISSUE TITLE
Test fails on macOS

### ISSUE THREAD

**Issue by styfle** [zeit/webpack-asset-relocator-loader#5]
```sh
$ yarn test
yarn run v1.15.2
$ npm run build && jest
npm WARN lifecycle The node binary used for scripts is /var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/yarn--1552870982981-0.9442051424146831/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @zeit/webpack-asset-relocator-loader@0.3.1 build /Users/styfle/Code/zeit/webpack-asset-relocator-loader
> ncc build src/asset-relocator.js

1290kB  dist/index.js
1290kB  [8752ms] - ncc 0.15.2
 FAIL  test/project.test.js
  ● should correctly run webpack build project-chunking

    expect(received).toBe(expected) // Object.is equality

    Expected: "asset.txt"
    Received: ""

      at eval (eval at <anonymous> (test/project.test.js:13:7), <anonymous>:5:39)
      at eval (test/project.test.js:13:7)
      at Object.<anonymous>.it (test/project.test.js:11:5)

 PASS  test/index.test.js (8.422s)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 31 passed, 32 total
Snapshots:   0 total
Time:        8.988s
Ran all test suites.
error Command failed with exit code 1.

```

**Comment by styfle** [comment]
@guybedford See the Circle CI output in #6

It looks like both Linux and macOS are failing the same test.
